'use server';
/**
 * @fileOverview A flow for generating new insights based on a conversation and a related image.
 *
 * - generateInsights - A function that handles the insight generation process.
 * - GenerateInsightsInput - The input type for the generateInsights function.
 * - GenerateInsightsOutput - The return type for the generateInsights function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateInsightsInputSchema = z.object({
  imageDataUri: z
    .string()
    .describe(
      "The AI-generated image as a data URI. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
  conversationContext: z
    .string()
    .describe('The context of the conversation (e.g., transcription or summary).'),
});
export type GenerateInsightsInput = z.infer<typeof GenerateInsightsInputSchema>;

const GenerateInsightsOutputSchema = z.object({
  insightsText: z
    .string()
    .describe('New insights, questions, or ideas generated by the AI. Svar på dansk.'),
});
export type GenerateInsightsOutput = z.infer<typeof GenerateInsightsOutputSchema>;

export async function generateInsights(input: GenerateInsightsInput): Promise<GenerateInsightsOutput> {
  return generateInsightsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateInsightsPrompt',
  input: {schema: GenerateInsightsInputSchema},
  output: {schema: GenerateInsightsOutputSchema},
  prompt: `Du er en AI-assistent, der specialiserer sig i at udlede dybere indsigter fra en kombination af en samtale og et visuelt billede relateret til samtalen.
Analysér følgende samtale kontekst og det tilhørende billede. Generer 2-3 nye, tankevækkende indsigter, spørgsmål eller idéer, der kan bruges som udgangspunkt for en ny samtale eller videre refleksion.
Formuler indsigterne som en sammenhængende tekst, der er klar til at blive brugt som input til en ny diskussion. Svar på dansk.
Hvis du ikke kan udlede meningsfulde indsigter, svar da med "Ingen specifikke nye indsigter kunne udledes."

Samtale Kontekst:
{{{conversationContext}}}

Relateret Billede:
{{media url=imageDataUri}}

Nye Indsigter (svar på dansk):`,
});

const generateInsightsFlow = ai.defineFlow(
  {
    name: 'generateInsightsFlow',
    inputSchema: GenerateInsightsInputSchema,
    outputSchema: GenerateInsightsOutputSchema,
  },
  async (input) => {
    if (!input.imageDataUri || !input.conversationContext) {
      console.warn("generateInsightsFlow: Manglende imageDataUri eller conversationContext. Returnerer tom indsigt.");
      return { insightsText: "Kan ikke generere indsigter uden både billede og samtalekontekst." };
    }
    const {output} = await prompt(input);
    if (!output) {
        throw new Error("Kunne ikke generere indsigter fra AI.");
    }
    if (typeof output.insightsText === 'string' && output.insightsText.trim() === "") {
      return { insightsText: "Ingen specifikke nye indsigter kunne udledes." };
    }
    return output;
  }
);
