'use server';
/**
 * @fileOverview A flow for generating new insights based on a conversation and a related image.
 *
 * - generateInsights - A function that handles the insight generation process.
 * - GenerateInsightsInput - The input type for the generateInsights function.
 * - GenerateInsightsOutput - The return type for the generateInsights function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateInsightsInputSchema = z.object({
  imageDataUri: z
    .string()
    .describe(
      "The AI-generated image as a data URI. Expected format: 'data:<mimetype>;base64,<encoded_data>'. Kan være en fejlbesked hvis billedgenerering fejlede."
    ),
  conversationContext: z
    .string()
    .describe('The context of the conversation (e.g., transcription or summary). Kan være en fejlbesked hvis tidligere trin fejlede.'),
});
export type GenerateInsightsInput = z.infer<typeof GenerateInsightsInputSchema>;

const GenerateInsightsOutputSchema = z.object({
  insightsText: z
    .string()
    .describe('New insights, questions, or ideas generated by the AI. Svar på dansk. Eller en fejlbesked.'),
});
export type GenerateInsightsOutput = z.infer<typeof GenerateInsightsOutputSchema>;

export async function generateInsights(input: GenerateInsightsInput): Promise<GenerateInsightsOutput> {
  return generateInsightsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateInsightsPrompt',
  input: {schema: GenerateInsightsInputSchema},
  output: {schema: GenerateInsightsOutputSchema},
  prompt: `Du er en AI-assistent, der specialiserer sig i at udlede dybere indsigter fra en kombination af en samtale og et visuelt billede relateret til samtalen.
Analysér følgende samtale kontekst og det tilhørende billede. Generer 2-3 nye, tankevækkende indsigter, spørgsmål eller idéer, der kan bruges som udgangspunkt for en ny samtale eller videre refleksion.
Formuler indsigterne som en sammenhængende tekst, der er klar til at blive brugt som input til en ny diskussion. Svar på dansk.
Hvis samtalekonteksten er en fejlbesked, eller hvis billedet ikke er tilgængeligt (angivet som en fejlbesked eller tom streng), svar da med "Ingen specifikke nye indsigter kunne udledes på grund af manglende input."

Samtale Kontekst:
{{{conversationContext}}}

Relateret Billede:
{{#if imageDataUri}}{{media url=imageDataUri}}{{else}}Intet billede tilgængeligt.{{/if}}

Nye Indsigter (svar på dansk):`,
});

const generateInsightsFlow = ai.defineFlow(
  {
    name: 'generateInsightsFlow',
    inputSchema: GenerateInsightsInputSchema,
    outputSchema: GenerateInsightsOutputSchema,
  },
  async (input) => {
    if (!input.conversationContext || input.conversationContext.trim() === '' || input.conversationContext.startsWith("Fejl") || input.conversationContext.startsWith("Kunne ikke")) {
      console.warn("generateInsightsFlow: Manglende eller ugyldig conversationContext.");
      return { insightsText: "Ingen specifikke nye indsigter kunne udledes på grund af manglende input." };
    }
    // Hvis imageDataUri indeholder en fejlbesked, vil Handlebars-logikken i prompten håndtere det.
    
    try {
      const {output} = await prompt(input);
      if (!output || typeof output.insightsText !== 'string' || output.insightsText.trim() === "") {
        console.error("GenerateInsightsFlow: Output fra prompt var ugyldigt eller manglede indsigter.", output);
        return { insightsText: "Kunne ikke generere indsigter." };
      }
      return output;
    } catch (error) {
      console.error("GenerateInsightsFlow: Fejl under prompt-kald", error);
      return { insightsText: "Fejl under generering af indsigter." };
    }
  }
);
